# Generated by Django 4.1.5 on 2023-07-20 05:19

from django.db import migrations, models
import django.db.models.deletion
import group.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('video', '0002_alter_video_options_alter_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=group.models.upload_image_media, verbose_name='GroupImage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
                ('videos', models.ManyToManyField(blank=True, to='video.video')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Group',
                'db_table': 'Group',
            },
        ),
    ]
