# Generated by Django 4.1.5 on 2023-06-19 12:46

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Videos', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=video.models.upload_video_media, verbose_name='video'),
        ),
        migrations.AlterModelTable(
            name='video',
            table='Videos',
        ),
    ]
