# Generated by Django 4.1.5 on 2023-07-21 08:27

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_options_alter_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=video.models.upload_image_media, verbose_name='GroupImage'),
        ),
    ]
